version: '2'

services:
  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx:latest
    restart: on-failure
    ports:
      - "${APP_PORT}:80"
    networks:
      - eth1
    volumes:
      - ./www:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    depends_on:
      - php-fpm
  php-fpm:
    container_name: ${APP_NAME}-php-fpm
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
    expose:
      - ${APP_XDEBUG_PORT}
    networks:
      - eth1
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./www:/var/www/html
      - ./php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php-fpm/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    links:
      - db
    depends_on:
      - db
  db:
    container_name: ${APP_NAME}-db
    image: mariadb:10.2
    restart: always
    ports:
      - "${DB_PORT}:3306"
    networks:
      - eth1
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
networks:
  eth1:
